### ISSUE TITLE
Discover on Controllers in multiple assemblies

### ISSUE THREAD

**Issue by kilroyFR** [heldersepu/Swagger-Net#100]
hey there again.

I needed to make an API that is split in several assemblies (one assembly with common controllers and another satellite assembly that is custom for the project (specific needs of the Customer)).
On common assembly the namespace is different from the custom assembly.

When starting application it seems to work but i noticed that controllers with same name (but not same namespace) are hidden from swagger. I used the UseFullTypeNameInSchemaIds in swagger.
The controllers only defined in satellite assembly are visible.
The controllers defined in both common and satellite assembly are not visible (while they are in different namespaces).

**Comment by heldersepu** [comment]
That is an interesting case ... but the workaround fix is really really simple, just name the controllers something unique
