### ISSUE TITLE
Including types that are not used in the definition

### ISSUE THREAD

**Issue by Steveiwonder** [heldersepu/Swagger-Net#101]
Heya,

How does one include a type that is not currently used, I have an enum which i'd like output in the swagger json but it's not in use on any models so it doesn't get included in the generate?

Thanks

S

**Comment by heldersepu** [comment]
Ye, look into IDocumentFilter here is an example:
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L579
