### ISSUE TITLE
Hide SwaggerUI GUI on production

### ISSUE THREAD

**Issue by kilroyFR** [heldersepu/Swagger-Net#103]
hey there, is there a simple way to disable displaying the SwaggerUI when application is pushed on production.
So far i tried conditioning using a classic #if !DEBUG

```
  /// <summary>
  /// Swagger Configuration
  /// </summary>
  public class SwaggerConfig
  {
    /// <summary>
    /// Register
    /// </summary>
    public static void Register()
    {
      var thisAssembly = typeof(SwaggerConfig).Assembly;

#if !DEBUG
      GlobalConfiguration.Configuration
          .EnableSwagger(c =>
              {
                // By default, the service root url is inferred from the request used to access the docs.
                // However, there may be situations (e.g. proxy and load-balanced environments) where this does not
                // resolve correctly. You can workaround this by providing your own code to determine the root URL.
                //
                c.RootUrl(req => "/my.API");
                // If schemes are not explicitly provided in a Swagger 2.0 document, then the scheme used to access
                // the docs is taken as the default. If your API supports multiple schemes and you want to be explicit
                // about them, you can use the "Schemes" option as shown below.
                //
                c.Schemes(new[] { "https", "http" });

                // Use "SingleApiVersion" to describe a single version API. Swagger 2.0 includes an "Info" object to
                // hold additional metadata for an API. Version and title are required but you can also provide
                // additional fields by chaining methods off SingleApiVersion.
                //
                c.SingleApiVersion("v1", "my.API");
```

But it still trying to load a Swagger page at /my.API/swagger/ui/index and i am getting an error 404.

Any help is much appriciated and i guess i am not the only one having this kind of requirements ?

Thanks

**Comment by heldersepu** [comment]
Interesting case ...
and I see how this could be useful in a multi environment project!
but no I have not seen this requirement before

Do you only want to "hide" the UI but keep the json doc?
if that is the case maybe a custom CSS can do the trick?

**Comment by heldersepu** [comment]
If you opt for the CSS trick you can add a css file to your project like:
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/Styles.css

then inject it with `InjectStylesheet`
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L251

**Comment by heldersepu** [comment]
...now that I read closely at the bottom of your comment:
>swagger/ui/index and i am getting an error 404.

Why is that an issue, if someone is trying to "hide" something like a 404 sound like it's hidden to me

**Comment by kilroyFR** [comment]
the 404 issue was error code on my side.
I could finally the trick above (using the #if DEBUG) to hide swagger and load a start page instead of the swagger page.

**Comment by heldersepu** [comment]
glad you got it to work ... but I think that your current implementation with the `#if !DEBUG` condition removing the EnableSwagger will more than just hide the UI, the swagger.json will not be generated
