### ISSUE TITLE
Malformed JSON from DateTime Range Min and Max

### ISSUE THREAD

**Issue by chillheart** [heldersepu/Swagger-Net#104]
We are using Swagger-Net to create Swagger 2.0 docs in a .NET 4.8 API. When I download the JSON and try to import it into various tools, we are getting an error that the JSON is malformed.

Here is the error that I am getting when I validate the JSON using swagger-cli:

```
Swagger schema validation failed.

  Expected type number but found type string at #/definitions/SystematicAccount/properties/startDate/minimum
  Expected type number but found type string at #/definitions/SystematicAccount/properties/startDate/maximum

JSON_OBJECT_VALIDATION_FAILED
```

This is the code that defines the model:
```C#
[Required(ErrorMessage = "StartDate is required.")]
[Range(typeof(DateTime), "1/1/1753 12:00:00 AM", "12/31/9999 12:00:00 AM", ErrorMessage = "Invalid StartDate")]
public DateTime StartDate { get; set; }
```

It appears that the swagger specification does not support date range minimum or maximum attribute in C#, so this should be ignored as it is causing the JSON to be invalid.

**Comment by heldersepu** [comment]
interesting I guess I never validated that

**Comment by heldersepu** [comment]
likely location for the fix if anyone wants to submit a PR:
https://github.com/heldersepu/Swagger-Net/blob/5536663e8ea0fd2c5b95b56ea344b37d07f22a9b/Swagger.Net/Swagger/Extensions/SchemaExtensions.cs#L23-L30

**Comment by chillheart** [comment]
Submitted pull request #105
