### ISSUE TITLE
why is there a dependency on  FromHeaderAttribute? 

### ISSUE THREAD

**Issue by livioc** [heldersepu/Swagger-Net#108]
Hi, I'm evaluating your project to replace Swashbuckle.WebApi, it seems very good but I don't understand why there's a dependency on FromHeaderAttribute, if I remove that package and compile the solution I don't get any error.
If it's not needed can I do a pull request for removing it? 
thanks

**Comment by heldersepu** [comment]
Yes that is used 
...and I'm also the author of FromHeaderAttribute:
https://github.com/heldersepu/FromHeaderAttribute

**Comment by livioc** [comment]
ok thanks, I asked that because I double-checked it without finding any use in the Swagger.Net project
