### ISSUE TITLE
I added an array type parameter method, the unit test result has two “[]”, maybe this reason, docs and ui can't read summary in xml, please verify this situation. 

### ISSUE THREAD

**Issue by jinyu52370** [heldersepu/Swagger-Net#109]
param is array
<img width="1280" alt="param is array" src="https://user-images.githubusercontent.com/63045341/156757695-63f0dcaa-192f-4c99-8acc-91170ef7bed7.png">

unit test comment
<img width="1280" alt="unit test comment" src="https://user-images.githubusercontent.com/63045341/156757739-dff393c1-2fca-4872-929d-91c66ed03ff3.png">

xml has summary
<img width="960" alt="xml has summary" src="https://user-images.githubusercontent.com/63045341/156758192-0475c53f-2792-4229-9289-de28f4f888e2.png">

docs no summary
<img width="306" alt="docs no summary" src="https://user-images.githubusercontent.com/63045341/156758209-027535fa-e87e-44db-a613-be551c73c14c.png">

**Comment by jinyu52370** [comment]
I found the same issues, ignore me...🤣

**Comment by heldersepu** [comment]
No worries... happy to see you found the issue
