### ISSUE TITLE
App_Start not found

### ISSUE THREAD

**Issue by Afsalmc** [heldersepu/Swagger-Net#123]
```Value does not fall within the expected range.
At C:\Users\afsalrahman\.nuget\packages\swagger-net\8.4.14.1\tools\Init.ps1:3 char:1
+ $SwaggerConfig = $project.ProjectItems.Item("SwaggerConfig.cs").FileN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException


App_Start not found

```
I'm getting this error. I have App_Start folder in the root of my project

**Comment by heldersepu** [comment]
that error is from here:
https://github.com/heldersepu/Swagger-Net/blob/master/Swagger.Net/Nuget/Tools/Init.ps1#L24-L33

```
try
{
    $AppStartDir = $project.ProjectItems.Item("App_Start").FileNames(1)
    MoveConfigFile $AppStartDir
}
catch
{
    Write-Host "App_Start not found! "
	#Write-Host $_.Exception
}
```
something is failed there you could also move the file manually
is the swagger page loading?

**Comment by Afsalmc** [comment]
There was no config before, right after that I tried manually copying the file and it solved my issues.  Reporting this event for further improvement to this awesome project.
