### ISSUE TITLE
Improve Nuget package (conditional SwaggerConfig && remove unused references)

### ISSUE THREAD

**Issue by pi3k14** [heldersepu/Swagger-Net#23]
Hi,

I have a selfhosted WebAPI project, and App_Start/SwaggerConfig dosn't work there.

I would prefer a "core" package without this helper.

**Comment by heldersepu** [comment]
The idea is to create on package that works for all...

**Comment by heldersepu** [comment]
@pi3k14 
Can you create a sample selfhosted WebAPI project that I can test the Nuget package. 
I would like to see how is the experience.

**Comment by heldersepu** [comment]
I think I'm going to take the powershell approach instead of the file template
https://everydaylifein.net/netframework/running-powershell-scripts-during-nuget-package-installation-and-removal.html

**Comment by heldersepu** [comment]
The Nuget package now has logic to determine if the SwaggerConfig should be added, here is the script:
https://github.com/heldersepu/Swagger-Net/blob/master/Swagger.Net/Nuget/Tools/Init.ps1

...and if you have time please test the new package: 
https://www.myget.org/feed/heldersepu/package/nuget/Swagger-Net

I will test for a few more days before I upload to Nuget

**Comment by pi3k14** [comment]
@heldersepu 
Hi,
just tried the new package, and it seems to work well. No App_Start folder, and I think you have fixed some model problems I encountered on my last try.
But - the package includes package references that are not necessary in a self-hosted environment, eg. WebActivatorEx and Microsoft.Web.Infrastructure, and some strange dependency on Microsoft.Bcl maybe indirectly from the other packages?

**Comment by heldersepu** [comment]
I'm glad it works!
If you see any problem (even minor details) let us know.
Keep in mind that the UI is a separate project:
https://github.com/swagger-api/swagger-ui

About the unnecessary references, that will be quite tricky to automatically remove...
Do you have any ideas how to (programmatically) detect & remove those?

**Comment by pi3k14** [comment]
Have investigated a bit, it doesn't seem to be necessary to include the package microsoft.net.http per doc "This package is ... only required for projects targeting .NET Framework 4.5, ... when consuming a library that uses this package." and then you also can exclude microsoft.bcl and microsoft.bcl.build.
There is also no need to use WebActivatorEx and App_Data/*, you can instead use System.Web.PreApplicationStartMethodAttribute ref. [why WebActivator](https://stackoverflow.com/questions/8987159/which-preapplicationstartmethod-should-i-use) and [how to use PreApplicationStartMethodAttribute](http://haacked.com/archive/2010/05/16/three-hidden-extensibility-gems-in-asp-net-4.aspx/) 
WebActivatorEx only was an advantage pre .Net 4.5

**Comment by heldersepu** [comment]
I removed the unused references ...

You can test it at MyGet:
https://www.myget.org/feed/heldersepu/package/nuget/Swagger-Net
