### ISSUE TITLE
async method not explored ?

### ISSUE THREAD

**Issue by Kaon68** [heldersepu/Swagger-Net#25]
Hi

This packages works quite fine out of the box, but - maybe i've missed a configuration - it seems to not be able to see Controller's public methods flagged with the async C# keyword.
"async" services work well. 

A reflection problem or something to do in configuration ?

thx :)

**Comment by heldersepu** [comment]
Do you have a minimal project reproducing this issue? 
That will significantly expedite troubleshooting

**Comment by heldersepu** [comment]
I was looking at some of my WebApi and I do have some methods that are ```async``` like this one:
https://github.com/heldersepu/TuroApi/blob/master/TuroApi/Controllers/SearchController.cs
And it shows just fine: http://turoapi.azurewebsites.net/swagger/ui/index#/Search/Search_GetByLocation

Without a minimal project reproducing this issue there is nothing I can do, I'm closing it for now, Please reopen if you can provide more details.

**Comment by Kaon68** [comment]
Hi again

I've looked closer to methods not being crawled by my swagger-net configuration, and I was mistaking : these are not only async methods ... just methods which routing have at least a parameter binding like [Route("MyService/{myParameter}"]

**Comment by heldersepu** [comment]
Nope, we have samples of those too, even have UnitTests with those, and it works fine.
Please create a minimal project reproducing your issue.

**Comment by heldersepu** [comment]
Just to test I created a controller with both ```async``` and ```[Route("MyService/{myParameter}"]``` it works fine:
http://swashbuckletest.azurewebsites.net/swagger/ui/index?filter=Async

and here is the code:
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/Controllers/AsyncController.cs

**Comment by Kaon68** [comment]
I know ... I'll try to get a minimal project with the same problem (for now, I can't reproduce this issue -__-)
How are methods crowled ? Knowing this may hint me why it's not working on my big project :-/

**Comment by heldersepu** [comment]
How are methods crawled?
**GetApiExplorer**

If you can add a controller to your solution (big project) with the same code as this one:
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/Controllers/ApiExplorerController.cs

The result should be a list of all methods like:
http://swashbuckletest.azurewebsites.net/api/ApiExplorer

**Comment by heldersepu** [comment]
Any luck with the minimal project ?

**Comment by Kaon68** [comment]
Sorry, I'm very busy for the moment ...
I keep in mind to test the GetApiExplorer method as soon as possible and keep you informed :)

**Comment by Kaon68** [comment]
Ok, I've found a track to my problem. My project use two special HttpParameterBinding inserted in GlobalConfiguration.Configuration.ParameterBindingRules.

Each hides some methods to the GetApiExplorer ... I don't know how for the moment.
