### ISSUE TITLE
Web API methods that return Lists render incorrect models in documentation

### ISSUE THREAD

**Issue by aphilpotts** [heldersepu/Swagger-Net#27]
Web API methods that return typed Lists show something strange as the model, for example...

		/// <summary>
		/// Get all filters
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		[Route("api/filter")]
		public List<FilterSummary> GetFilters()
		{
                      ...
		}

renders as:
[
xml: OrderedMap { "name": "FilterSummary", "wrapped": true }
LI.Models.WebApi.FilterSummary{...}]

**Comment by heldersepu** [comment]
What is strange about that?

**Comment by heldersepu** [comment]
*IF* that is an issue I think it will be a [Swagger-UI](https://github.com/swagger-api/swagger-ui) issue:
http://petstore.swagger.io/#/pet/findPetsByStatus
They do have the same pattern on the demo

**Comment by aphilpotts** [comment]
So sorry, I misinterpreted what I was seeing and didn't notice I could drill through to the type, all is well, closing
