### ISSUE TITLE
Fix issue where examples are not serialized properly

### ISSUE THREAD

**Issue by JustASquid** [heldersepu/Swagger-Net#28]
I have been running into an issue where examples aren't serialized properly - they are generating with PascalCase property names instead of being correctly serialized to CamelCase:

      "example": {
        "EmployeeExpenses": {
          "12345": [
            {
              "EmployeeExpenseCategoryId": "98",
              "EmployeeExpenseCategoryName": "My expense category",
              "Notes": "Some notes",
              "Amount": 12.34,
              "TaxCode": "42rty",
              "TaxRate": 0.5,
              "TaxCodeDisplayName": "Tax Code Display",
              "LocationId": "39",
              "LocationName": "My Location",
              "EmployeeId": "1235",
              "EmployeeName": "Bob Bobberson"
            }
          ]
        },
        "PayRunId": 999
      },

It seems that in Swashbuckle, these issues were marked as won't-fix.

[Issue 694](https://github.com/domaindrivendev/Swashbuckle/issues/694)
[Issue 709](https://github.com/domaindrivendev/Swashbuckle/issues/709)

Is it possible that we could resolve these issues in this library instead?

**Comment by heldersepu** [comment]
Sure we can fix it... You want to start a PR?

**Comment by heldersepu** [comment]
I was testing and I do not get any errors on my end....
Would this cause any issues or is this just a cosmetic thing?

**Comment by JustASquid** [comment]
@heldersepu not sure what you mean here, can you clarify?

**Comment by heldersepu** [comment]
Even if the property names do not have the "proper case" I do not get any errors

**Comment by JustASquid** [comment]
Yeah, there aren't any errors/exceptions if that's what you mean (I asusme you're referring to when it's imported in Swagger-UI?). It's 'cosmetic' in that sense I suppose, but it's obviously important to show our customers resource examples with correctly cased properties.

**Comment by heldersepu** [comment]
Look at this:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/Company/Company_Post
I think that is the correct case...

But even If I manually change the case of the properties and execute I get the right response. 
What I'm trying to say is that this is a very low low priority issue, I personally would not spend any time on it, ... but if is important to you and want to research it, fix it and send a Pull Request I will merge it.

**Comment by JustASquid** [comment]
@heldersepu It works for you because the server's serialization settings are set up to be flexible. That's all well and good, but from a consumer's perspective (e.g. with an example for a response resource), showing them one case type as an example and then having the actual API return a different case type is bad - who knows how they have set up their serialization. You can't break their expectations like that, it's the whole point of having API documentation in the first place. So I'd say that examples, at least for response resources, are useless until this is fixed.

That said, I understand if you don't have the time to fix it right now. I may be able to start on a PR in a few days, if you have any hints as to where I should be looking in the codebase (i.e. what's actually serializing out those examples to the JSON?) that would be much appreciated.

**Comment by heldersepu** [comment]
Take a look a these links:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/Company/Company_Get
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/Company/Company_Post

The case of the properties is matching exactly what I have in my model:
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/Models/Company.cs

I think there is something else at play in your api...

**Comment by JustASquid** [comment]
Well yes, the whole problem is that the casing is coming from the C# models directly as opposed to the serializer settings (e.g. in our app, all the object properties are uppercase in C# but they are all serialized to lowercase when calling into/responding from the API).

**Comment by heldersepu** [comment]
Now I see why the issues were marked as won't-fix. I'm leaning that way...
And all the other crazyCases can go with an IDocumentFilter.
My recommendation change your code to have the case you want to see

**Comment by JustASquid** [comment]
@heldersepu Not only is it completely impractical to change the casing on hundreds of classes to deal with this single case, I would argue such a significant change shouldn't be required. We're not doing anything unusual, uppercased properties serialized down to lowercase is the norm in C# APIs AFAIK?

If it's possible to manually force the example serializer to do what we need by using the IDocumentFilter, I'm definitely happy to work around it that way. Is it possible?

**Comment by heldersepu** [comment]
I kind of stopped reading when you said "all the object properties are uppercase" I don't know if you are serious or this is some kind of weird prank...

**Comment by JustASquid** [comment]
We may be on a slightly different page here. I should have said that all the class properties are uppercase, as they are in every C# application I've ever worked on:

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

**Comment by JustASquid** [comment]
Oh... heh, I just realized I've been using inconsistent terminology here. When I say 'uppercase' I mean PascalCase of course, not UPPER_CASE, which would indeed be crazy as you say!

**Comment by heldersepu** [comment]
Yes we definitely are on a different page, heck we are on different books.
That link has no reference to UPPERCASE that is usually used for constants...

With an IDocumentFilter you have full control over the final swagger doc, I have some examples here:
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L353

**Comment by JustASquid** [comment]
Hopefully we're a bit more on the same page now (see my previous clarification there), sorry for the confusion. 

ok so it looks like the IDocumentFilter solution would have me regexing over the examples JSON and changing the casing that way. I don't really like that solution as it's fairly brittle and prone to weird edge cases. Ideally I'd be able to control the serialization settings directly on whatever is generating the JSON representations of the objects I'm passing in as examples, if that makes sense? If that really isn't possible then I suppose I can look at doing it a less elegant way.

**Comment by heldersepu** [comment]
why would you be regexing over anything?
So we don't waste any more time with theories can you create an example and start on the IDocumentFilter and I will help you finish it

**Comment by JustASquid** [comment]
OK, hopefully I'll have some time soon to play around with it. 

My question is simple though:
Is there any way to control the serialization settings on the serializer that's generating the JSON for the examples?

**Comment by heldersepu** [comment]
nope, there is nothing special on serializer for the examples
