### ISSUE TITLE
How to support token parameter which in the Headers?

### ISSUE THREAD

**Issue by lixinchuang** [heldersepu/Swagger-Net#30]
some parameters  must be transfered through headers,  does swagger-Net support this requirement

**Comment by heldersepu** [comment]
Yes it does... Here is an example:
http://swashbuckletest.azurewebsites.net/swagger/ui/index?filter=Value#/ValueProvider/ValueProvider_Put

**Comment by heldersepu** [comment]
You will need to use an IOperationFilter see ***AddRequiredHeaderParameters*** here:
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L488

**Comment by patrickbussmann** [comment]
@heldersepu I want to do the same but it's not working.
So there is no `AddSecurityRequirement` function in your code.
Your current link of your comment https://github.com/heldersepu/Swagger-Net/issues/30#issuecomment-344259201 is also an empty line of documentation.

Can you make an example, please?
Only adding this line makes no effect to the request header.

    c.ApiKey("apiKey", "header", "API Key Authentication");

And P.S. even this is different than your example here. https://github.com/heldersepu/Swagger-Net/wiki/2-Troubleshooting#describing-securityauthorization-schemes

Thanks in Advance!

**Comment by heldersepu** [comment]
@patrickbussman
Yes i think that I updated the ApiKey method and did not update the documentation

**Comment by heldersepu** [comment]
I think this example could be helpful:
https://github.com/heldersepu/nhc-noaa/blob/master/nhc-noaa/App_Start/SwaggerConfig.cs

**Comment by heldersepu** [comment]
@patrickbussmann Can you provide a sample project of what you are trying to do?
