### ISSUE TITLE
Add support for showExtensions configuration

### ISSUE THREAD

**Issue by andremachado** [heldersepu/Swagger-Net#31]
Hello,

Swagger-UI 3.5.0 supports the new config showExtensions. It allows one to display vendor extensions on the UI. It would be nice to have Swagger-Net support it. 

Not sure if you accept MRs, but if you don't have time I could try to work on it.

Thanks!

**Comment by heldersepu** [comment]
Sounds like a plan, start on the that Pull request...

**Comment by andremachado** [comment]
Done! I've just opened it

**Comment by heldersepu** [comment]
Looks good, your PR has been merged.

**Comment by andremachado** [comment]
Thanks! Do you know when we will have an updated package with this change?

**Comment by heldersepu** [comment]
I was going to wait until friday for a new version of the UI
... but  it looks like you need it here you go:
https://www.nuget.org/packages/Swagger-Net/8.3.5.3
Just give it a few minutes for Nuget to finish indexing it

**Comment by andremachado** [comment]
NICE! Thanks a lot!
