### ISSUE TITLE
Possible BSD copyright non-compliance

### ISSUE THREAD

**Issue by yojagad** [heldersepu/Swagger-Net#34]
The screen.css file with the line "/* Original style from softwaremaniacs.org (c) Ivan Sagalaev <Maniac@SoftwareManiacs.Org> */" apparently may not be BSD compliant...

Is this based off of default.css within "https://github.com/isagalaev/highlight.js" ? I could be wrong, but are you sure Swagger-net is compliant according to the license here? 

https://github.com/isagalaev/highlight.js/blob/master/LICENSE

**Comment by heldersepu** [comment]
Thanks for the report,  screen.css has been removed from the project

**Comment by yojagad** [comment]
Thank you! Was also wondering if you would publish a new version to nugget soon.

**Comment by heldersepu** [comment]
Done: https://www.nuget.org/packages/Swagger-Net/8.3.8.101
