### ISSUE TITLE
When i use MultipleApiVersions

### ISSUE THREAD

**Issue by WoJoinGitHub** [heldersepu/Swagger-Net#38]
When i use MultipleApiVersions,the API list is null. but the SingleApiVersion is working.

**Comment by WoJoinGitHub** [comment]
when i use Swashbuckle is working,but Swashbuckle is too slow. so i hope get you help. thinks.

**Comment by heldersepu** [comment]
We need more details...

**Comment by WoJoinGitHub** [comment]
![tim 20180131085644](https://user-images.githubusercontent.com/9404436/35599661-d21b0f36-0664-11e8-9bb5-42310b124f8b.png)
![tim 20180131085828](https://user-images.githubusercontent.com/9404436/35599679-ef973b3e-0664-11e8-9b96-07dd2834df4b.png)
 configuration.EnableSwagger(
                            "{apiVersion}/swagger",
                            swagger =>
                            {                         
                                swagger.MultipleApiVersions(
                                    (apiDesc, targetApiVersion) => apiDesc.GetGroupName() == targetApiVersion,
                                    info =>
                                    {
                                        foreach (var group in apiExplorer.ApiDescriptions)
                                        {
                                            var description = "跨境医疗项目,API在线文档.";

                                            if (group.IsDeprecated)
                                            {
                                                description += " <br/><b>此 API 版本已弃用！</b>";
                                            }
                                            info.Version(group.Name, $"版本 {group.ApiVersion}")
                                                .Contact(c => c.Name("Shijun Liu"))
                                                .Description(description);
                                        }
                                    });  
                                swagger.BasicAuth("basic")
                                    .Description("基础授权");                             
                                //api注释
                                swagger.IncludeXmlComments(XmlCommentsFilePath);
                            })
                         .EnableSwaggerUi(swagger =>
                         {                           
                             swagger.DocumentTitle("跨境医疗项目");
                         });


![Uploading TIM图片20180131092943.png…]()

**Comment by heldersepu** [comment]
Do you have that project on GitHub?

**Comment by WoJoinGitHub** [comment]
no ! this our company project

**Comment by heldersepu** [comment]
With the information you have provided I can not troubleshoot...
Can you create a minimal project reproducing the issue?

**Comment by WoJoinGitHub** [comment]
but when i use SingleApiVersion is true

![tim 20180131093437](https://user-images.githubusercontent.com/9404436/35600652-0c25b4e2-066a-11e8-95af-d114708ca532.png)

**Comment by WoJoinGitHub** [comment]
ok ! let me try! thinks

**Comment by WoJoinGitHub** [comment]
https://github.com/webapiSample/webapi
hi! this project have the same question!

you can change the nuget package
 //using Swashbuckle.Application;
    using Swagger.Net.Application;

**Comment by WoJoinGitHub** [comment]
Thank you very much!

**Comment by erndob** [comment]
I know this is old, but in case someone else gets this issue, for me the problematic line was:

>             (apiDesc, targetApiVersion) => apiDesc.GetGroupName() == targetApiVersion,

The issue is that Swagger-Net converts the version to uppercase(unlike swashbuckle), while ApiDescription GroupName is the original you have in the path. So if you are like me, you have all your paths as v{apiVersion} and you moved to Swagger-Net, nothing works anymore because v{apiVersion} != V{apiVersoin}.

>             (apiDesc, targetApiVersion) => apiDesc.GetGroupName().ToUpperInvariant() == targetApiVersion,
