### ISSUE TITLE
how to order controller by  controller name  ?

### ISSUE THREAD

**Issue by dcdlove** [heldersepu/Swagger-Net#39]
Aftet I have configed SwaggerConfig.cs as follow, the order of the controller become disordered:
`c.IncludeXmlComments(GetXmlCommentsPath("Api.xml"));`

by the way, the comments of "Api.xml" is chinese

**Comment by dcdlove** [comment]
``  c.OrderActionGroupsBy(new SortByControllerName());`
` class SortByControllerName : IComparer<string>
    {
        int IComparer<string>.Compare(string x, string y)
        {
            return x.CompareTo(y);
        }
    }

**Comment by heldersepu** [comment]
What version are you using?

**Comment by Spmr03** [comment]
we are using version 1.0.0.0

**Comment by Spmr03** [comment]
It should be like this:
![eo h6 28y _dq3qoz_r](https://user-images.githubusercontent.com/22342802/35761398-e733ea86-08c2-11e8-87fd-5954b464ed06.png)

But it become like this after we add comments xml 
![tim 20180203090809](https://user-images.githubusercontent.com/22342802/35761406-074488ee-08c3-11e8-9b8c-e55bfa1461a6.png)

**Comment by heldersepu** [comment]
Sorry check your version against Nuget

**Comment by heldersepu** [comment]
https://www.nuget.org/packages/Swagger-Net
Latest is 8.3.9.301

**Comment by dcdlove** [comment]
id="Swagger-Net" version="8.3.4.402"

**Comment by heldersepu** [comment]
Time to Update!
Please use the latest that should solve this order prolem

**Comment by dcdlove** [comment]
good, thank you！
