### ISSUE TITLE
ApiVersion parameter in query instead header

### ISSUE THREAD

**Issue by ecoburotic** [heldersepu/Swagger-Net#40]
Hello,

I thinks have found a bug in parameter generation.

I recently use MultipleApiVersions instead SingleApiVersion.

We use header param for ApiVersionning (because we don't want change URL at each version) but that not work in Swagger (but a simple REST call works fine!)

Swagger thinks my param is a query param but not, it's an header param.

You can see my hotfix here : https://github.com/ecoburotic/Swagger-Net/commit/d148de13f80a5110c8781b7e13c62d8b39c135cc

I can't make a pull requests because I have other commits.

My server code (for information, if that can help you to reproduice)

In WebApiConfig.cs
```
 // Configuration et services API Web
 config.AddApiVersioning(o =>
 {
     o.ReportApiVersions = true;
     o.AssumeDefaultVersionWhenUnspecified = false;
     o.ApiVersionReader = new HeaderApiVersionReader("api-version");
     o.ApiVersionSelector = new CurrentImplementationApiVersionSelector(o);
 });
 
 var apiExplorer = config.AddVersionedApiExplorer(options =>
 {
     options.GroupNameFormat = "V.V";
     options.DefaultApiVersionParameterDescription = "Version de l'API";
 });
```

In SwaggerConfig.cs
```
 c.MultipleApiVersions(
     (apiDesc, targetApiVersion) =>
     {
         targetApiVersion = targetApiVersion[0] + "." + targetApiVersion[1];
 
         List<string> apiVersions = apiDesc.ActionDescriptor.GetApiVersions().Select(apiVersion => apiVersion.ToString()).ToList();
 
         return apiVersions.Contains(targetApiVersion);
     },
     (vc) =>
     {
         var t = GlobalConfiguration.Configuration.Services.GetApiExplorer();
         var t2 = t.ApiDescriptions;
 
         foreach (ApiDescriptionGroup item in ((VersionedApiExplorer)t).ApiDescriptions)
         {
             vc.Version(item.ApiVersion.ToString().Replace(".", string.Empty), "EcoServiceREST API v" + item.ApiVersion.ToString());
         }
     });
```

**Comment by heldersepu** [comment]
Looking into it...

**Comment by heldersepu** [comment]
You say:
> Swagger thinks my param is a query param but not, it's a header param.

Do you have a sample controller/action(s) showing that?

**Comment by heldersepu** [comment]
I merged what I consider relevant from the commit you sent, here is my change: https://github.com/heldersepu/Swagger-Net/commit/2c4055c7dc9d944c290961d5cd18d7042f1216c7
