### ISSUE TITLE
Cant remove required in complex data type

### ISSUE THREAD

**Issue by Nazgaul** [heldersepu/Swagger-Net#42]
Hi. I got this model

```c#
public class SomeRequest
{
    [DefaultValue(null)]
    public Loc Location { get; set; }
}

public class Loc
{
    [DefaultValue(0f)]
    public float Longitude { get; [UsedImplicitly] set; }

    [DefaultValue(0f)]
    public float Latitude { get; [UsedImplicitly] set; }
}
```
I want the location to be optional in swagger. and yet i can't seems to manage that. the json result is:

```json
parameters: [
{
    name: "Location.Longitude",
    in: "query",
    required: true,
    type: "number",
    format: "float"
},
{
    name: "Location.Latitude",
    in: "query",
    required: true,
    type: "number",
    format: "float"
}
],
```

Any idea how to manage that? thanks

**Comment by heldersepu** [comment]
Not sure why yours are marked required, do you mind sharing more details...

Here is mine:
http://swagger-net-test.azurewebsites.net/swagger/ui/index?filter=Location#/Location/Location_Get2

And the code behind is here:
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/Controllers/LocationController.cs

**Comment by Nazgaul** [comment]
In your example Location come as stand alone object. this is working. Mine is in a complex type. e.g. class SomeRequest is the model and nested inside it is the Location.

**Comment by heldersepu** [comment]
Can you please create a minimal example reproducing your issue?

**Comment by heldersepu** [comment]
I've tried everything possible and I'm unable to reproduce your issue.

Please create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve).

**Comment by Nazgaul** [comment]
I create a small asp.net core web api git to show you the issue.
this is the link. https://github.com/Nazgaul/SwaggerIssue

As i told before this is a complex model with nested class location ( your example are not)
the ui is not working in this project ( although

 it should ) but the json generator is. attach is the screenshot and the issue is highlighted.
![capture](https://user-images.githubusercontent.com/3366179/37023665-4fab32b6-212f-11e8-8b8e-68c987d6cbe3.PNG)

**Comment by Nazgaul** [comment]
I create a small asp.net web api in github that simulate my problem. this is the link

https://github.com/Nazgaul/SwaggerIssue

the ui is not working but the json generation is.
in my example location class is nested inside another class that is the model. in your example that is not the case. 
I added Default attribute(0f) that should fixed the required but its not. 

![capture](https://user-images.githubusercontent.com/3366179/37023875-f36f6156-212f-11e8-8be1-baceb6fd7d6b.PNG)

**Comment by heldersepu** [comment]
It looks like your are using Swashbuckle.AspNetCore:
https://github.com/Nazgaul/SwaggerIssue/blob/master/WebApplication1/Startup.cs#L12
not Swagger-Net, report this to the correct project
