### ISSUE TITLE
New Endpoint URL format breaks OAuth redirects

### ISSUE THREAD

**Issue by dolkensp** [heldersepu/Swagger-Net#43]
Previously I was using swagger + swashbuckle without issue, and simply registered the single redirect url and we were good.

Upon updating to Swagger-Net (based on latest swagger-ui) however, the URLs no longer use a `#hash-format` but instead a `?query-parameter` to select which API version you're looking at.

This is affecting the redirect_url for oauth2 clients, meaning I now need to register a client for every api version.

This is further complicated by the fact that our selected identity provider enforces a unique client_id, meaning we can't register multiple redirect_urls for the same client_id, so the end-user is forced to update the client_id when changing end points too.

Previous redirects all went via `o2c.html`, now occasionally they go via `oauth2-redirect-html?urls.primaryName=swagger%2Fdocs%2FAPI`

Interestingly, if I auth on the initial page, THEN swap to the selected api version, the auth is remembered. I can then log out, then log in successfully.

However if I browse to the api version first, then attempt to log in, the altered redirect url is used.

**Comment by heldersepu** [comment]
Issue fixed, Thanks for the PR will publish to Nuget shortly...

**Comment by heldersepu** [comment]
I don't have a sample project that can reproduce this behavior... Can you create one? 
Would love to publish it as part of my final checks... I have some tests here:
http://swagger-net-test.azurewebsites.net/swagger/ui/index

**Comment by dolkensp** [comment]
Thanks for the quick response!

I'll try and take a look tonight - I also want to investigate [this alternative](https://github.com/dolkensp/Swagger-Net/commit/c2db4b314306deae4c775ebd7756c311cb100d4e) to forcing uppercase for version numbers, but that will require some more testing before I open any PRs - I'll try work the oauth issue into the testing for that.

**Comment by heldersepu** [comment]
What do you mean by:
> collect the scopes from the OperationFilter dynamically

Can you point me to the code you are looking at?

**Comment by dolkensp** [comment]
Basically, instead of:

  c.OAuth2("oauth2")
      .Description("OAuth2 Implicit Grant")
      .Flow("implicit")
      .AuthorizationUrl($"{Global.AuthRoot}issue/oauth2/authorize");
      .Scopes(scopes =>
      {
          scopes.Add("public:read", "Read access to public resources");
          scopes.Add("public:write", "Write access to public resources");
      });

I was considering having my `c.OperationFilter<ApiScopeOperationFilter>()` automatically inject the scopes that are in use into the oauth config.

Not something that can easily be made generic I don't think - and unfortunately the OperationFilters run long after the oauth config has been executed, so can't even use a static variable and reference that.

This leaves me either looking at my own assembly-scan, or potentially try a different type of filter.

Not something to worry about for this project I don't think.

**Comment by dolkensp** [comment]
Regarding improving the performance of the filters - it appears they're already pipelined anyways?

https://github.com/heldersepu/Swagger-Net/blob/master/Swagger.Net/Swagger/SwaggerGenerator.cs#L201

I'm not sure that you'd be saving much performance by consolidating them, and it *does* make things extremely configurable.
