### ISSUE TITLE
Provide Configuration for Swagger Documentation Syntax - YAML

### ISSUE THREAD

**Issue by Joe89Degrees** [heldersepu/Swagger-Net#47]
This is more of a feature request than an issue, because the software works extremely well (especially for my more advanced requirements such as adding Vendor Extensions and adding required Headers to the Swagger UI via Operation Filters) - nice work! I am looking for a way to export the Swagger document in YAML format. The JSON format is perfect for me, but unfortunately, I am tasked with providing the document in YAML format. I suppose I could write a JSON to YAML converter myself (for now), but figured I would reach out to see if this is something that could be put into a feature enhancement list. 

I am hoping "document syntax" or "document markup" could be configurable via Swagger.config, or maybe provide an "Export" button on Swagger UI, allowing the consumer to choose "Export as JSON" or "Export as YAML". Specifically, I am tasked with exporting the document in the same way you can choose YAML on the Swagger website here: https://editor2.swagger.io .. For now, I am copying the JSON, going to that Swagger website editor, pasting the JSON and exporting/saving as a YAML document. I do have a workaround, but was thinking this would be an awesome feature for those of us tasked with providing the document in YAML format.

P.S. Truly an awesome tool; by far the best ASP.NET Web API NuGet package for Swagger UI.

**Comment by heldersepu** [comment]
I honestly do not see a need to support both formats. That's why I will close this issue as "wontfix"

...But a while back I was playing with something like that take a look into my YamlDocumentFilter :
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L378

**Comment by Joe89Degrees** [comment]
Agreed, and I hate that I need to support YAML. The ONLY reason I thought to open an issue, thinking that others were also facing this problem, because Swagger.io has YAML all over the place, and they had seem to use it more than JSON: https://swagger.io/docs/specification/basic-structure/

Thanks for the link to the YamlDocumentFilter, greatly appreciated!
