### ISSUE TITLE
With `SwaggerDocsConfig.DescribeAllEnumsAsStrings()`, defaults remain integer.

### ISSUE THREAD

**Issue by Tungsten78** [heldersepu/Swagger-Net#50]
enum
```
public  enum Filter {first, second, third};
```

controller snippet
```
[Route("test")]
public HttpResponseMessage Get(Filter filter = Filter.first)
```

snippet of generated swagger.json:
```
"parameters": [
                    {
                        "default": 0,
                        "enum": [
                            "first",
                            "second",
                            "third"
                        ],
                        "in": "query",
                        "name": "filter",
                        "required": false,
                        "type": "string"
                    }]
```

swagger ui
![image](https://user-images.githubusercontent.com/3805338/39062064-9757b176-4483-11e8-85fc-929bc5b4aef3.png)
![image](https://user-images.githubusercontent.com/3805338/39062211-1dc329e8-4484-11e8-9129-4e54226e2436.png)

*Expected Result:*
* swagger.json - `"default":"first"`
* Swagger UI - defaults to "first" in dropdown when using "Try it out"

*Actual Result:*
* swagger.json - `"default":0`
* Swagger UI - defaults to "--"

**Comment by Tungsten78** [comment]
@heldersepu - thanks!

**Comment by heldersepu** [comment]
You are very welcome!
Looking at your profile this looks like your first reported BUG congrats! Now start coding!!!

**Comment by heldersepu** [comment]
Here is a sample showing that it works
http://swagger-net-test.azurewebsites.net/swagger/ui/index#/NestedEnum/NestedEnum_Get

I will wait until tomorrow to push to Nuget to wait for a new version of the UI
