### ISSUE TITLE
Documentation Improvement Suggestion

### ISSUE THREAD

**Issue by georgeslegros** [heldersepu/Swagger-Net#53]
Hello,

Small suggestion: on the custom asset, it is possible to add a custom requestInterceptor in the SwaggerUIBundle object, which I believe is intended. 
I suggest adding some information on the documentation about this, especially about the fact that the request parameter passed to the function HAS to be returned.
If you don't return the request object, the request seems to still be properly executed but the CURL box is broken.

**Comment by heldersepu** [comment]
I think this is about the Swagger-UI not this project...
That s a different project

**Comment by heldersepu** [comment]
Anything regarding the SwaggerUIBundle you should report it here:
https://github.com/swagger-api/swagger-ui
