### ISSUE TITLE
Versions cannot be set in lowercase

### ISSUE THREAD

**Issue by vivek201** [heldersepu/Swagger-Net#55]
https://github.com/heldersepu/Swagger-Net/blob/50b00eb140da4d3de8b53f6c72a618865aefc694/Swagger.Net/Application/VersionInfoBuilder.cs#L17

This line is causing versions to be defined in uppercase.

#54 I created a pull request as well.

**Comment by heldersepu** [comment]
Comments from the PR:

This was done to make the Version case insensitive...

See these two resolve to the same
http://swagger-net-test.azurewebsites.net/swagger/docs/V1
http://swagger-net-test.azurewebsites.net/swagger/docs/v1

What are you trying to fix?
Can you share your config?
Or better yet create a minimal project reproducing your issue and I will help you get to the bottom of this issue, we can not go back to forcing a case sensitive version

**Comment by vivek201** [comment]
The issue was in my ResolveVersionSupportByRouteConstraint function that was checking uppercase Version with my lowercase routes. Fixed that and now everything works. Thanks!

**Comment by heldersepu** [comment]
When you get a chance please share the code (before and after) of your `ResolveVersionSupportByRouteConstraint` function so others with similar issue could benefit.
