### ISSUE TITLE
XmlCommentsIdHelper.AppendMethodName should use [generic type => int] lookup instead of increasing the number

### ISSUE THREAD

**Issue by vforvoid** [heldersepu/Swagger-Net#58]
https://github.com/heldersepu/Swagger-Net/blob/aea8a43db9a409deadd7be9172784656e16514c8/Swagger.Net/Swagger/XmlComments/XmlCommentsIdHelper.cs#L121

Good day and thank you for this nice library.
I found an issue with `AppendMethodName` method: I think it can't just increment the `generic` number. This number designates zero-based index of a type's generic parameter. So, in case if I have a class:

```
class SomeGenericClass<TFirst, TSecond, TThird>
{
    public void SomeMethod(TFirst foo, TThird bar)
    {

    }
}
```

Current `AppendMethodName` implementation will create ``M:SomeGenericClass`3.SomeMethod(`0,`1)`` XML method name for `SomeMethod` while the right one is ``M:SomeGenericClass`3.SomeMethod(`0,`2)`` because `TThird`'s position in declaring class typeparams is 2, not 1. So I think it should use lookups instead of simply incrementing the number.

**Comment by heldersepu** [comment]
You are right! and at the moment I do not have a solution for that...

**Comment by vforvoid** [comment]
You can use this code to get a mapping between parameter name and its position
```

static IDictionary<string, int> GetTypeParameterPositions(Type type)
{
	var result = new Dictionary<string, int>();
	if (!type.IsGenericType)
		return result;
	var genericTypeDefinition = type.GetGenericTypeDefinition();
	foreach (var genericArgument in genericTypeDefinition.GetGenericArguments())
		result.Add(genericArgument.Name, genericArgument.GenericParameterPosition);
	return result;
}
```

**Comment by heldersepu** [comment]
Correction added in v8.3.17.3##

**Comment by vforvoid** [comment]
@heldersepu I don't think it fixed.
Consider following test

```
    public abstract class Blob<T1, T2> : ApiController
    {
...
        /// <summary>PATCH</summary>
        public int Patch(T2 y, IEnumerable<T1> x) { return 0; }
    }

    [Test]
    public void Method_from_generic_action_patch()
    {
        var methodInfo = typeof(BlobController).GetMethod("Patch");
        var comment = methodInfo.GetCommentIdForMethod();
        Assert.AreEqual(CTRLR + "Blob`2.Patch(`1,System.Collections.Generic.IEnumerable{`0})", comment);
    }
```

https://github.com/heldersepu/Swagger-Net/blob/master/Swagger.Net/Swagger/XmlComments/XmlCommentsIdHelper.cs#L84
This line should also check if the `type.IsInterface` is true otherwise it will miss IEnumerable
Even if it does check for `IsInerface` though it will put `IEnumerable{`0}` as its second argument. Because `ExpandGenericArgsIfAny` has no idea about original method's generic type params. You HAVE to pass the dictionary to this method somehow.

https://github.com/vforvoid/Swagger-Net/commits/fixed-generics-support-for-xml
Please consider checking my last 2 commits, I can create PR once again if you wish.

**Comment by heldersepu** [comment]
Yes please submit a new PR
Make sure to use latest

**Comment by vforvoid** [comment]
I think it works now on my end now. Or we are missing some tests that fails it :) 
Thanks a lot!
