### ISSUE TITLE
Removing routes from the Paths list doesn't remove the controller completely from the swagger UI

### ISSUE THREAD

**Issue by bennyr103** [heldersepu/Swagger-Net#61]
It used to be enough to remove a path from the SwaggerDocument paths list to hide a controller from the swagger UI in swashbuckle using a documentfilter. That doesn't seem to work here. An empty list item with the controller name remains on the Swagger UI. Is that the expected behavior? Does it have to be removed from the definitions list as well now?

```
var paths = new Dictionary<string, PathItem>(swaggerDoc.paths);
                    swaggerDoc.paths.Clear();
                    foreach (var api in apiExplorer.ApiDescriptions)
                    {
                        var route = "/" + api.Route.RouteTemplate.TrimEnd('/');
                        if(ViewableAPIs.Any(x => route.Contains(x)))
                        {
                            var path = paths.TryGetValue(route, out PathItem pathItem);
                            if (pathItem != null)
                                swaggerDoc.paths.Add(new KeyValuePair<string, PathItem>(route, pathItem));
                        }
                    }
```

**Comment by bennyr103** [comment]
It's the SwaggerDocument tags that are showing up. Clearing that list out seems to remove the empty items from the api list.

Is this the right way to do it?

**Comment by heldersepu** [comment]
Yes the tag was the issue
