### ISSUE TITLE
On the use of nginx reverse proxy

### ISSUE THREAD

**Issue by dcdlove** [heldersepu/Swagger-Net#62]
Swagger-Net" version="8.3.9.301"
```
nginx config
server {
    listen       8001;                      
    server_name api.jhtmsf.com;    			
    location / {
		proxy_pass  http://127.0.0.1:8007;
		proxy_set_header Host $host:$server_port;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header REMOTE-HOST $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		client_max_body_size    2000m;		
		root   html;
		index  index.html index.htm;
    }
}
```

![tim 20180722181650](https://user-images.githubusercontent.com/10043691/43044603-ba53630e-8ddb-11e8-822c-d908a35ecc90.jpg)

Thank you very much for your selfless dedication. 
Can you solve this problem through configuration?

**Comment by heldersepu** [comment]
Not sure what "this" problem is can describe what you are truing to do?

**Comment by dcdlove** [comment]
The Url addresses of the API documents that are opened after using the nginx reverse proxy are inconsistent.

**Comment by heldersepu** [comment]
Can you provide steps to reproduce this, I know nothing about nginx...

You should look at the generated HTML code specifically:

```
window.swaggerNetConfig = {
   rootUrl: 'http://swagger-net-test.azurewebsites.net',
```

Also on the generated JSON there is
```
"host": "...",
```

Make sure that matches what you need

**Comment by dcdlove** [comment]
**thank you for your patient guidance~~~**
------------------------------------------------------------
swaggerNetConfig   screenshot

![tim 20180724075006](https://user-images.githubusercontent.com/10043691/43108794-34aa9538-8f16-11e8-9f93-326f77281895.png)

![tim 20180724075857](https://user-images.githubusercontent.com/10043691/43109067-7298b68a-8f17-11e8-91c2-f6431e75acdb.jpg)

i doubt it is after Nginx ，the host values taken by swaggerNet are inconsistent.

**Comment by heldersepu** [comment]
I think all you have to do adjust the rootUrl in the config

**Comment by dcdlove** [comment]
thank you. I already know how to deal with this problem.
