### ISSUE TITLE
what about OData api endpoints ?

### ISSUE THREAD

**Issue by figuerres** [heldersepu/Swagger-Net#64]
I found no info on this on SO
I am going to take a look at what is needed to use the 
https://github.com/rbeauchamp/Swashbuckle.OData/tree/master/Swashbuckle.OData
code as your project is based on the same stuff...

unless i can get OData to work i can't use this package.

**Comment by heldersepu** [comment]
I personally never used OData ...
But if an OData project is a WebApi there should not be a problem picking endpoints

**Comment by figuerres** [comment]
by default Swashbuckle does not pickup the OData items unless you add the Swashbuckle.Odata package.
I am looking at the code to see if i can make it work with your version of Swagger generator.
there are a couple of places where the OData extension has  references to Swashbuckle core and Interfaces.
as i have time i will see  but i can't dive into this full time , if i can make it work i  follow up.

**Comment by figuerres** [comment]
just wanted to let you know, i took the Odata Extensions package source and have almost got it to match up with your version, had to update several things as it was using some older packages for parts of Web Api and Microsoft OData, Json.Net and so on...
if i get it to build and run i will post back again , i can't say that i can do a lot to keep updating and such but perhaps some other folks can help ....   the one thing i have no clue about is how to make it packaged for re-dist to other users, never done that before.

**Comment by heldersepu** [comment]
If this does not interferes with the WebApi projects ....
we should consider including the functionality in the project, from what I can see is just a few files

**Comment by figuerres** [comment]
When i have it working i will post it and you can see if you want to combine it.

no it does not block or harm the basic web api parts, it just adds the OData end points.

OData adds metadata that describes the controllers and methods  that web api does not have.

i  changed the namespace and class names in my local copy to match Swagger.Net  so that will make it easier to combine with the rest of your version of code.

**Comment by figuerres** [comment]
found one area that your version of the code differs and may need chnages, see this link:
[SchemaRegistry.cs](https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Swagger/SchemaRegistry.cs)


the OData Extension as written to pluginto SwashBuckle uses 9 items on the constructor

**Comment by heldersepu** [comment]
I was comparing the SchemaRegistry.cs : 
https://diffnow.com/files/__edp_output__18a88ad5-1ab8-4fe0-9e6a-27d98e454619.htm
And at some point I most have consolidated all the loose items in the constructor...

**Comment by figuerres** [comment]
Yeah, i think what you just posted must be right, i work for a company near tampa fl by the way , so i have two pc's and switch back and forth between them, so sometimes i may have to let one thing set while i get the other task done....  we have a large complex project with a large list of web api's and OData APi's and a front end app using Angular 4 / TypeSCript   I work with 2 other developers on this.
we also have  Identity Server doing OAuth / OpenID   and Microsoft SQL Server Reporting Services.
I stay fairly busy with all the hats a wear at work :--)

**Comment by heldersepu** [comment]
That does not sound too complicated :) 
let's migrate all that from Azure to AWS ... and don't forget to TerraForm all your infrastructure

**Comment by figuerres** [comment]
just wanted to say that i have the code part working but been super busy.

also i wonder if you know anything or have any ideas about this:
we have a large api set  that we would like to let some users only see the swagger for some of the api methods not all of them.

we are a shipping company, so our main api set has things like creating and updating staff logins but we also have api calls for tracking a package or creating a new shipping label.

i would like to allow customers a small set of things that they can do and not show them 500 api  methods.

so i can create a second web site for them , that will work but then two sites to maintain and keep the code synced between.
or if the user logs in and i see they are a customer then swagger only shows the apis for them.
if i can do that then no need to do multiple web sites.

i know that swagger can have basic security / login but will limiting the swagger doc require a custom addon class  to render the right json based on user roles ??
any ideas on that ?

**Comment by figuerres** [comment]
I got some time today and this weekend to follow up on this, i have learned something new that might just make this work with out even needed the code from that other project.

https://github.com/Microsoft/aspnet-api-versioning

This is also the home of the ASP.NET API versioning API explorers that you can use to easily document your REST APIs with Swagger:

ASP.NET Web API Versioned API Explorer ( nuget | quick start | samples ) 
Replaces the default API explorer in your Web API applications

ASP.NET Web API with OData API Explorer ( nuget | quick start | samples ) 
Adds an API explorer to your Web API applications using OData v4.0


looks like if i add this package and chnage a small bit of my current odata config that the apiexploroer service will add the Odata items to the rest of the api data and give it back to your code.

i am testing it out and will post back when i see what happens.

**Comment by figuerres** [comment]
basically i have it working!!!
had to add   c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());
OData will always have 2 get's on each entity
get  - no param gets all rows in a table
Get with a key like Id -- get one record from a table where key is the id value 

what Odata does is you have an entity model   that has the tables in the db with the relations.
then you make a controller for each table and by default Post == insert
Patch == update
Delete == Delete
and two get's 

i see some other details to sort out but using the updated api-explorer gets the raw data 
there are a few things the project needs to do - like a line config.addodataapiexplorer();
and then your code will get the Odata bits along with the rest of the api methods.

no need for adding any package to your stuff, no need for an OData package based on the old code.
just use the current Microsoft Packages and configure them.

**Comment by figuerres** [comment]
just a note on progress: got it working yes. right now i have some code hacked in that may not be what you want for the final , will have to work on how to best modify the generator and put the OData code in a namespace etc...
api explorer takes a really long time with my project to get the data, the json generation is fine, it's all in the api explorer getting the api data, i have over 600 api methods , between regular api and OData.
after it generates the client works as expected. will have to see if i can pre-generate my json and serve up a static copy.

**Comment by heldersepu** [comment]
Now I see why you need to secure swagger routes, 600 api methods is a LOT!
I think you have some architectural problems... if I was in your shoes I would push to refactor into multiple  loosely coupled web services, potentially a Microservices Architecture. 

____

> serve up a static copy.
sounds like you need to enable [AllowCachingSwaggerDoc](https://github.com/heldersepu/Swagger-Net/blob/master/Swagger.Net/Nuget/Content/App_Start/SwaggerConfig.cs.pp#L44)

**Comment by figuerres** [comment]
the company i work for is a logistics company, we are in the process of building a new overall system. so we have all of the elements of a medium sized business, clients, our facilities, our staff, contractors, packages, cod, line hauls, google maps to plot routes, markets, zipcodes .... and one and on....

**Comment by reginaldovillela** [comment]
Hello,

How do I use it with the https://github.com/Microsoft/aspnet-api-versioning library to create versioning?

Thank you

**Comment by heldersepu** [comment]
Closing this issue adding the OData Extension functionality to the project will add a lot of references that inflate the project for everyone, that should be an external project
