### ISSUE TITLE
How I do Authorization Bearer with Swagger-Net

### ISSUE THREAD

**Issue by vitorlans** [heldersepu/Swagger-Net#65]
Hello, 

I'm looking a way to use Bearer Authorization with Swagger-Net, but I didn't find way to do that, 
It's possible help me, what is the best way to do that using swagger-net

Thanks.

**Comment by heldersepu** [comment]
Your best bet will to post those questions on Stackoverflow ...

**Comment by JFolinus** [comment]
I was also having a similar problem as @vitorlans, I asked a question on Stackoverflow yesterday but nothing so far https://stackoverflow.com/questions/52433796/send-bearer-token-in-swagger-using-swagger-net.  Thanks for your work with this framework.

**Comment by heldersepu** [comment]
@JFolinus I see you are using ApiKey... I have used that before successfully, let me look for an example...
