### ISSUE TITLE
Feature: secure swagger route

### ISSUE THREAD

**Issue by figuerres** [heldersepu/Swagger-Net#67]
Ok i know there are multiple answers to this and that is part of why i am posting this.
with swashbuckle and with nswag and with swagger-net  each package is generating the json and bundling the UI but each user has to then figure out how to make sure that only the right users can browse the UI and see the JSON.
seems like this should be part of the standard packages as the packages are setting up a route that the user had limited control over.
so possibly adding some configure options might be a good move to make this better ?

also related i see that Open API V3   changes the Swagger json spec to better work with OpenID Connect.
I use Identity server and Open ID Connect so a move to better work with that would be a real plus for me.

**Comment by heldersepu** [comment]
Sorry I never had the need to do this...
...and as you already found out:
https://github.com/domaindrivendev/Swashbuckle/issues/804#issuecomment-231212206
there is very little progress on this topic

But you are welcome to send a PR

**Comment by figuerres** [comment]
I am hoping to have some stuff to send you later this week, see my work on OData that is getting close to complete!

**Comment by heldersepu** [comment]
Sounds good, remember to include unit tests

**Comment by heldersepu** [comment]
...after doing some more reading on this topic ... I have mixed feelings about it.

Adding this could provide a false sense of security to new users, the only protection here is "Security through obscurity" and that is a BAD practice!  

Also this is going to break all the Swagger Codegen tools out there, with this they will need to integrate some form of authentication.

**Comment by figuerres** [comment]
Well i sure do not want to go the path of  "Security through obscurity"  !
and breaking things is for sure an issue.

what i would like to see is something like the standard bearer token  support.

the idea i have in mind is that the api site may already have the token support in place and the real problem is hooking into the route or the file requests.

and having the swagger json file be public readable is not really a good idea.

i have a coupe of ideas and if i can see a good way to do this i will let you know.
my first thing is to get my OData swagger at 100% and then to address the login issues.
we are working on giving a customer limited access to some api's but not everything.
part of this may be done with the versions, but what i would rather see in the end is the claims and roles as the control method.

**Comment by heldersepu** [comment]
Also this goes beyond browsing the UI, this is going to break all the Swagger Codegen tools out there, with this they will need to integrate some form of authentication, something that I have not seen yet.

Have you used the Codegen in Visual Studio there is no place for token there:
![](https://www.red-gate.com/simple-talk/wp-content/uploads/2017/06/word-image-44.png)
![](https://www.red-gate.com/simple-talk/wp-content/uploads/2017/06/word-image-45.png)

**Comment by figuerres** [comment]
interesting what the spec says about filtering the document...
[OpenAPI Specification 3.0.1](https://swagger.io/specification/#securityFiltering)
which can also break code gen tools.
i think that we will see the tools changing , or that users may get a json file and not use a link. and or add login support / api key support etc....

**Comment by heldersepu** [comment]
Closing this as is something way beyond Swagger-Net
