### ISSUE TITLE
Saving the swagger json to disk, how to make it match the web version

### ISSUE THREAD

**Issue by figuerres** [heldersepu/Swagger-Net#68]
I wrote some code to add to the SwaggerDocsHandler   to save a copy of the swagger json to disk.
that way if the swagger is not in memory but is in the disk folder i could read that file and cache that to memory.  this way between publishing an update the full generation could happen just one time.
i have the code using newtonsoft json to save and read the data but on read i get an error about the $ref elements.

so i saved a copy and then ran the web site and saved the doc from the web site url.
the web site url version is much shorter than the newtonsoft version.

do i need to use the code in the ContentFor() method to make it right ?
 var content = new ObjectContent(typeof(SwaggerDocument), swaggerDoc.SwaggerDocument, result.Formatter, result.MediaType);

should i actually save this ObjectContent version of the data ???

or is there another method  i should use to do this ?

**Comment by figuerres** [comment]
found that i just needed to ask newtonsoft to handle the $ref differently on read and it looks like that will work!
 serializer.MetadataPropertyHandling = MetadataPropertyHandling.Ignore;

**Comment by heldersepu** [comment]
Me guess you fix issue...
