### ISSUE TITLE
how to configure the swagger info json ?

### ISSUE THREAD

**Issue by figuerres** [heldersepu/Swagger-Net#69]
i do not see a way in the current code to configure the swagger to put in values for the info object.
if that is true and i have not missed something then perhaps we can add that to the enable swagger / options later...

**Comment by figuerres** [comment]
[SwaggerDocument.cs](https://github.com/heldersepu/Swagger-Net/blob/master/Swagger.Net/Swagger/SwaggerDocument.cs)
has a class info that has contact, license and terms of service.
i have not found a way to set them in the config.
or am i missing something ?

**Comment by heldersepu** [comment]
Look into IDocumentFilter, I think that is what I do here:
http://swagger-net-test.azurewebsites.net/swagger/ui/index

Code behind:
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs
