### ISSUE TITLE
return type pdf / document filter

### ISSUE THREAD

**Issue by figuerres** [heldersepu/Swagger-Net#70]
i created a filter to set the response type to pdf
the ui shows the response type but i still get a text box that is labeled
"Unrecognized response type; displaying content as text."
the headers show that it is a pdf

content-disposition: inline; filename=Label4x6_v3development11872371541680226306.pdf 
 content-type: application/pdf 

any idea if there is a way to get it to open acrobat or show the pdf ?
or is that not possible to do ?

**Comment by heldersepu** [comment]
You should not need a filter for that, I have some somethig like that for images:
https://github.com/heldersepu/Swagger-Net-Test/blob/c9b554fde26367418c84fcd3682d308ae1b40d11/Swagger_Test/Controllers/PngImageController.cs

**Comment by figuerres** [comment]
the media type will work for an image but not for a pdf.
i did some searching and found a few different results.
it looks like the content disposition and the media type both play a role in what happens and it looks like in my case we will just allow swagger to not display the file.
image works, native html and javascript know what to do.
pdf needs to goto a handler / plugin in the browser, but swagger tries to render text.

possibly just add a note in your docs that pdf will not work.
the Open api site is also not planning on helping with this case.

**Comment by heldersepu** [comment]
Can you share some code on what you have...

**Comment by figuerres** [comment]
i can give you a bit of it , really just try to send a pdf file back via web api.
we generate a shipping label via MS SQL Reporting services get the stream and pass it back as the response content.
if i have a client app save the content to a file it works perfectly. so the bits i stream back are a valid binary pdf file.

`         ms = new MemoryStream(   wc.DownloadData("URL")));`

`  ms.Position = 0;
                    r = Request.CreateResponse();`

`                    r.Headers.CacheControl = new CacheControlHeaderValue()
                    {
                        NoCache = false,
                        Private = true
                    };
                    r.Content = new StreamContent(ms);
                    r.Content.Headers.ContentLength = ms.Length;
                    r.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/pdf");
                    r.Headers.TransferEncodingChunked = true;
                    r.Content.Headers.ContentDisposition =
                                new System.Net.Http.Headers.ContentDispositionHeaderValue(
                                    "inline")
                                { FileName = "label" + TrackingNumber+ ".pdf" };`

` return r;`

client code is http client calls web api and then

`   var response = httpClient.GetAsync(urlBuilder.Uri.AbsoluteUri).Result;
            if (!response.IsSuccessStatusCode) {
                throw new Exception(String.Format("HTTP Failure {0} - {1}", response.StatusCode, response.ReasonPhrase));
            }
            using (var file = System.IO.File.Create("C:\\web\\label_"+TrackingNumber + ".pdf")) { 
                var contentStream = response.Content.ReadAsStreamAsync().Result; 
                contentStream.CopyTo(file); 
                file.Flush(); 
            }
            MessageBox.Show("Saved File in web folder  "+ "C:\\web\\label_" + TrackingNumber + ".pdf", "Got Label");`

all that works.
swagger just does not let the browser handle the content, it tries to put it in a text area.

**Comment by heldersepu** [comment]
**If** I understand correctly you want the Swagger-UI to show you the PDF embedded in the "Response body" section, honestly I do not see the usefulness of that... 
I think that if you change the ContentType to `application/octet-stream` it will show a link to download instead of text:
http://swagger-net-test.azurewebsites.net/swagger/ui/index#/Image/Image_Put

From my experience with the UI that is not going to happen any time soon, unless you take it upon yourself to write a PR introducing that functionality then convince the Swagger-U team that is a good idea and they merge it

**Comment by figuerres** [comment]
this is just a "nice to have" not a "must have"

we are preparing a site that our customers who have IT staff can use to create shipping labels for us to pickup packages. 

 so that if they have a program that ties into their data they can automate stuff.

so for showing them that we can generate the printable pdf it would be nice to show the pdf.
but my sample app can prove that we are generating a valid pdf for them.

the octet-stream also did not work. 
the only thing i did not try is to make the reply as "attachment" in place of "inline"
 at this point i am good with what we have.

the key thing is swagger and my sample app together prove that our api's work as advertised and they can use them.

my boss is very happy right now, he is also a developer so he understands that we can't always have it all.

**Comment by heldersepu** [comment]
Yep nice to have some times take a lot of time to do and not worth it...
I ran into something like that with SVG images 

Strange that the octet-stream did not work for you... 
You do see it working on the link I sent you right?
