### ISSUE TITLE
TypeExtensions generate bad IDs

### ISSUE THREAD

**Issue by dolkensp** [heldersepu/Swagger-Net#71]
In [TypeExtensions.cs](https://github.com/heldersepu/Swagger-Net/blob/d70d1dd54205e80962e2c5d17192c592c7dc81d7/Swagger.Net/Swagger/Extensions/TypeExtensions.cs#L25), you're denoting generic classes using square brackets.

Once you try and parse the generated definitions in editor.swagger.io, these will force an error:

```
Semantic error at paths./awards/v0/public/awardtiers.get.responses.200.schema.$ref
$ref values must be RFC3986-compliant percent-encoded URIs
```

This is because RFC3986 reserves square brackets for denoting ip addresses.

```
A host identified by an Internet Protocol literal address, version 6
[RFC3513] or later, is distinguished by enclosing the IP literal
within square brackets ("[" and "]").  This is the only place where
square bracket characters are allowed in the URI syntax.  In
anticipation of future, as-yet-undefined IP literal address formats,
an implementation may use an optional version flag to indicate such a
format explicitly rather than rely on heuristic determination.
```

I'm happy to open a PR for this, but wanted some input on what you thought a suitable replacement might be.

The reserved characters from RFC3986 are:

```
      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

With that in mind, we can't use square brackets, or commas, so I was hoping to open discussion about viable alternatives

* C# uses `Generic<Type1,Type2>`
* Swagger-Net uses `Generic[Type1,Type2]`

**Comment by dolkensp** [comment]
One option would be `GenericOfType1AndType2`

I'm not sure how readable we expect nested generics to be, but without a suffix, this scheme may run into occasional collisions.

**Comment by heldersepu** [comment]
I'm not sure I understand what the problem is... 
can you provide a sample Api reproducing this issue
or add a unit tests that shows the error

**Comment by dolkensp** [comment]
Browse to http://editor.swagger.io/

Select File -> Import URL and pass your demo URL:

http://swagger-net-test-multiapiversions.azurewebsites.net/swagger/docs/DEFAULT

In particular I was focusing on these errors, caused by the use of generics

```
Semantic error at paths./api/Blob.put.parameters.0.schema.$ref
$ref values must be RFC3986-compliant percent-encoded URIs
Jump to line 571

Semantic error at paths./api/Default.post.responses.200.schema.$ref
$ref values must be RFC3986-compliant percent-encoded URIs
Jump to line 879
```

**Comment by heldersepu** [comment]
So weird that those errors do not show in the online validator:
https://online.swagger.io/validator/debug?url=http://swagger-net-test-multiapiversions.azurewebsites.net/swagger/docs/DEFAULT

**Comment by dolkensp** [comment]
I think if you're conforming to that spec...

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#referenceObject

> The Reference Object is a [JSON Reference](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-02#section-3)

Which states

> The "$ref" string value contains a URI [[RFC3986](https://tools.ietf.org/html/rfc3986)], which identifies the location of the JSON value being referenced.  It is an error condition if the string value does not conform to URI syntax rules.

Which brings us back to the start - so technically, those warnings are correct.

**Comment by heldersepu** [comment]
I guess we should look how others handle issues like this...
will try doing my WebApi on https://github.com/RSuter/NSwag let's see what are the differences

**Comment by heldersepu** [comment]
I was looking at how NSwag generates those Definitions and it seems to use a patter similar to what you mention `GenericOfType1AndType2`

Here is what I have:
`"AnotherFoo[Foo]"`
And here is what NSwag spits out:
`"AnotherFooOfFoo"`

**Comment by heldersepu** [comment]
Try with the latest version:
https://www.nuget.org/packages/Swagger-Net/8.3.19.502
