### ISSUE TITLE
Examples in separate compilable classes

### ISSUE THREAD

**Issue by korser1** [heldersepu/Swagger-Net#72]
Could you please consider this feature? 
https://github.com/mattfrear/Swashbuckle.Examples

By this one you are able to create compilable examples in the project
Thanks!

**Comment by heldersepu** [comment]
I do not see the advantage of that...
We do have support for examples.

 if you have a specific requirement please be precise on what's needed.

**Comment by korser1** [comment]
We have different nested classes and complex objects with our API.
When you add an example it into xml comment you have to track changes in a class structure.
The second reason - enum conversion. For example, you have enum, but in the API have to set the numeric value of enum.
The third one, but not too much neecessary, date/time values. Recompile the project and such values will be updated. Helpful when the project is in the development.

If you have an advice to use it through [SwaggerExample], I appreciate this!

**Comment by korser1** [comment]
FYI: Just created a fork from Swashbuckle.Examples - https://www.nuget.org/packages/Swagger.Net.Examples/

Will add to git soon.

**Comment by heldersepu** [comment]
Sounds like a plan!

Would be nice to keep the project names consistent, compare with:
- https://www.nuget.org/packages/Swagger-Net
- https://github.com/heldersepu/Swagger-Net
