### ISSUE TITLE
Is it possible to inject content into each request/response section?

### ISSUE THREAD

**Issue by josh-endries** [heldersepu/Swagger-Net#73]
We have some calls that return response codes within the content (in addition to the HTTP response code). I would like to generate some content to output (preferebly in C# via reflection) and have it output in the response section for the call. Is this possible without just hacking the DOM?

**Comment by heldersepu** [comment]
Sure it is possible, look into the DocFilters, I have a few examples:
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L198
