### ISSUE TITLE
required is not working with fluent api

### ISSUE THREAD

**Issue by Bykiev** [heldersepu/Swagger-Net#75]
Hello, I'm using fluent API and Model fields are not marked as required

**Comment by heldersepu** [comment]
An example reproducing your issues will be nice I personally do not use
that...

**Comment by Bykiev** [comment]
Model:

    public class Company
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public int DepartmentId { get; set; }
        public virtual Department { get; set; }
   }

DB mappings:

    public class CompanyMap : EntityTypeConfiguration<Company>
    {
        public CompanyMap()
        {
            this.ToTable("Company");
            this.HasKey(_ => _.Id);
            this.Property(_ => _.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            this.HasRequired(_ => _.Department).WithMany(_ => _.Company).HasForeignKey(_ => _.DepartmentId);
        }
    }

**Comment by heldersepu** [comment]
I see what you are doing...
Unfortunately that is not something i would support.
You should create your modules the swagger way, here is an example:
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/Models/Company.cs

**Comment by Bykiev** [comment]
@heldersepu, finally I solved the issue by using this [ISchemaFilter](https://stackoverflow.com/questions/46576234/swashbuckle-make-non-nullable-properties-required)

anyway, thanks for your time!

**Comment by heldersepu** [comment]
yes you can hack your way to anything with an ISchemaFilter or an IDocumentFilter but that is not the proper solution for this case...

You should be decoreating your models correctly, like:

```
    public class Company
    {
        /// <summary>The Unique Company ID</summary>
        /// <example>123</example>
        [Required]
        [DefaultValue(456)]
        public int Id { get; set; }

        [Required]
        [DefaultValue(null)]
        public int? MyId { get; set; }

        /// <summary>The Company Name</summary>
        /// <example>Acme co</example>
        [DefaultValue("My Company")]
        public string Name { get; set; }

        [Range(0.1, 0.99)]
        public double ErrorMargin { get; set; }

        [MinLength(5)]
        [MaxLength(250)]
        [RegularExpression(@"^[^@\s]+@[^@\s]+\.[^@\s]+$")]
        public string Email { get; set; }
```

**Comment by Bykiev** [comment]
sure, but I'm integrating it to the existing project where is fluent annotaion is used, so I don't want to specify the Required attribute (again).
