### ISSUE TITLE
Feature: Show enums even though numeric values used on wire

### ISSUE THREAD

**Issue by katit** [heldersepu/Swagger-Net#77]
Currently c.DescribeAllEnumsAsStrings can either show that we take strings on a wire or numbers (and then we see choices in description)

In our case we do use numbers when data transmitted/received but we would like to show string representations of those enums for documentation purpose. So, if we have enum like this:

enum Status : byte {
Active = 1,
Inactive = 0
}

We like documentation to show "0" but model show something like "0-Inactive, 1-Active", not just number 0,1

**Comment by heldersepu** [comment]
I have tests on this:
http://swagger-net-test.azurewebsites.net/swagger/ui/index?filter=Default#/Default/Default_Post

On and enum like your:
```
enum Status : byte {
    Active = 1,
    Inactive = 0
}
``` 
what you request: `0-Inactive` or `1-Active` are not valid values...
 the API can take `1` or `Active` not  `1-Active`

**Comment by katit** [comment]
Absolutely right, API can take only numbers in our case, and this screenshot below correct, however I'd like to somehow display what those values actually mean. When setting c.DescribeAllEnumsAsStrings it does show strings but it's incorrect, because API needs numbers

![image](https://user-images.githubusercontent.com/8389381/58447973-eb8b4480-80cb-11e9-8f23-0b3cb5d84d39.png)

When I set option I see this (which is incorrect but has enum strings).
![image](https://user-images.githubusercontent.com/8389381/58448107-694f5000-80cc-11e9-9e4c-df875d5af7e2.png)

**Comment by heldersepu** [comment]
Do you have a sample reproducing your issue?

**Comment by katit** [comment]
Attached sample WebAPI project

JsonAttribute set to serialize enums as numbers. Enum set as enum:byte
GET api/values shows 
![image](https://user-images.githubusercontent.com/8389381/58496964-8cb3e280-8140-11e9-8b3a-edeadbdbacdf.png)

Also, I noticed another problem. Json serializer set to do CamelCase naming but Swagger does not see this and shows properties upper-cased

[WebApplication2.zip](https://github.com/heldersepu/Swagger-Net/files/3228818/WebApplication2.zip)

**Comment by heldersepu** [comment]
why do you say this is incorrect ?
![image](https://user-images.githubusercontent.com/8389381/58448107-694f5000-80cc-11e9-9e4c-df875d5af7e2.png)
That looks fine to me

**Comment by heldersepu** [comment]
In your code sample, you are seen:
![image](https://user-images.githubusercontent.com/8389381/58496964-8cb3e280-8140-11e9-8b3a-edeadbdbacdf.png)

because you have not enabled DescribeAllEnumsAsStrings

**Comment by heldersepu** [comment]
> All enums in our case of : byte type, not int32
The spec only has int32 & int64 for integer type
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

**Comment by katit** [comment]
> because you have not enabled DescribeAllEnumsAsStrings
I did not enable it because we do not serialize Enums as strings. API users have to send number, not string 

But I do want users of our API to know what number to send for what enum value, hence dilemma. I want it to be auto-documented, but it's not string. This is why I marked it as "Feature". Swagger need to display strings but use numbers 

> The spec only has int32 & int64 for integer type 
Got it, that makes sense then.

Should I post it as separate issue?
_Also, I noticed another problem. Json serializer set to do CamelCase naming but Swagger does not see this and shows properties upper-cased_

**Comment by heldersepu** [comment]
> API users have to send number

No they don't, the web api can "translate" the enum from number or string here is an example:
- http://swagger-net-test.azurewebsites.net/api/EnumTest?rule=None
- http://swagger-net-test.azurewebsites.net/api/EnumTest?rule=0

That is this endpoint:
http://swagger-net-test.azurewebsites.net/swagger/ui/index?filter=EnumTest#/EnumTest/EnumTest_Get


____

If you want to add something else to the integer type you can post it on their repo:
https://github.com/OAI/OpenAPI-Specification
But I strongly doubt it will be added

**Comment by katit** [comment]
> No they don't, the web api can "translate" the enum from number or string here is an example:

Ok, maybe WebApi can "translate" when we post data TO server(also we don't really need that). However, on GET - our server will return numbers only because we set it so. So, if we want to document it correctly - we need to show users that return value will be number. And then users won't know what "names" for those enum values going to be.

**Comment by heldersepu** [comment]
Now I see what you mean...

Sorry but that is not Swagger-Net problem, but a design decision... 
- You can make your API always use strings (like I did on my example) and problem solved.
- Or if you prefer to return numbers you will have to add the appropriate documentation in a description somewhere, could be something like:
http://swagger-net-test.azurewebsites.net/swagger/ui/index?filter=Location#/Location/Location_Get2

**Comment by heldersepu** [comment]
Here is a sample of adding description to an enum:
http://swagger-net-test.azurewebsites.net/swagger/ui/index?filter=EnumTest#/EnumTest/EnumTest_Post
the code for that is here:
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/Controllers/EnumTestController.cs#L20

**Comment by katit** [comment]
Description would work just fine for us. The only problem - it's EF entity/enum and those are auto-generated files

**Comment by heldersepu** [comment]
Sorry @katit but this is not something that Swagger-Net can magically fix for you.
The options are there you just have to code it, you can look into using an iDocumentFilter, I have some examples here:
- https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L559
- https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L583
