### ISSUE TITLE
Annotations to describe the parameters of the actions and the controller in class

### ISSUE THREAD

**Issue by DiegoGarciaMartin** [heldersepu/Swagger-Net#78]
Hello,

I need annotations to describe the parameters of the actions and the controller in class.

Like this:

```
[SwaggerDescription("Controller description")]
public class ExampleController : ApiController {
    [SwaggerExample("id", "Parameter description")]
    public IHttpActionResult ExampleAction(string id) {
    }
}
```

I've been looking at the tests and I think it's not implemented.

Will it be available in the future?

Regards.

**Comment by heldersepu** [comment]
you should use the `///` to document your controllers and actions then enable: 
IncludeAllXmlComments

The end result should look like:
http://swagger-net-test.azurewebsites.net/swagger/ui/index#/ApiExplorer/ApiExplorer_Get

**Comment by DiegoGarciaMartin** [comment]
Hello,

I'm trying to use XML comments in actions.

I have activate the option with IncludeAllXmlComments, but it doesn't work.

The descriptions only apear if they are written in a separate XML document. If I write them in the class not. 

In your project, I deleted the file XmlComments.XML and it works, and the descriptions apear. I don't know if anything else is missing from the project, besides the IncludeAllXmlComments.

Regards.

**Comment by DiegoGarciaMartin** [comment]
Hello,

I was trying to use annotations because XML comments didn't work.

I had the option IncludeAllXmlComments activate but I still needed to activate "XML Documentation File" in the buid.

![1](https://user-images.githubusercontent.com/10710391/58616664-864b7500-82be-11e9-9686-020a8d104a75.png)

Now, It works.

Regards and thanks.

**Comment by heldersepu** [comment]
Im glad you got it to work! 
On my test project the xml file I have it as an embedded resource, that makes it easier later for deployment
