### ISSUE TITLE
x-requested-with header

### ISSUE THREAD

**Issue by garyw90** [heldersepu/Swagger-Net#79]
In our API, we use OAuth2 authentication with a package called SecureAuth.  When I use Authorize to get a token, the CORS preflight is failing.  The error in the Chrome console shows:

Access to fetch at 'https://xxxx.org/secureauth12?response_type=id_token&redirect_uri=http%3A%2F%2Flocalhost%3A4143%2Fcontent%2Foauth.html&scope=openid%20email%20profile&client_id=zzzzzzz' from origin 'http://localhost:4143' has been **blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response**.

I suspect this is because the JavaScript is trying to send X-RequestWith: XMLHttpRequest header.  Is there any way to disable this, short of building a custom version of Swagger-Net?  One of our other teams is using Swashbuckle, but that has not been active for some time.

**Comment by heldersepu** [comment]
You don't have to build a custom version...
Just submit a PR and I will merge it

**Comment by garyw90** [comment]
Hi Helder, thans for the quick reply.

I downloaded the source from gitHub earlier today, but it does not include any of the JavaScript that you have as embdeded resources in the current package in NuGet( 8.3.22.101).  That is where I would need to make the change.

**Comment by heldersepu** [comment]
the embedded resources (JavaScript files and others) are from the Swagger-UI:
https://github.com/swagger-api/swagger-ui

**Comment by garyw90** [comment]
Hi Helder, thanks for the quick response
Since the issue seems to be in the swagger-ui project, I would be reluctant to modify that to remove the header.

My current thought is to create a custom index.html file, reference that from swagger config, and in that custom file add a requestInterceptor.  Thoughts?

**Comment by heldersepu** [comment]
a custom index.html, hummm... I see a big loop of trial and error
Good luck

**Comment by heldersepu** [comment]
the embedded resources (JavaScript files and others) are from the
Swagger-UI:
https://github.com/swagger-api/swagger-ui
Are you sure the problem is in the UI?

**Comment by heldersepu** [comment]
And don't  be afraid to submit PR to the swagger-ui team I have contributed there and team is very active.

If you want to discuss further hit me directly  via email... my email is on my profile
