### ISSUE TITLE
Support of OAuth2 through browser

### ISSUE THREAD

**Issue by garyw90** [heldersepu/Swagger-Net#80]
Is it possible to configure Swagger-Net to perform OAuth2 authentication via the browser?  In our case, we need to perform a GET request to initiate login, and our identity provider uses two factor authentication.  That requires additional forms that the simple authorization built into swagger-ui does not appear to support, unless I am missing something...

**Comment by heldersepu** [comment]
Yes here is an example:
http://swagger-net-test.azurewebsites.net/swagger/ui/index

The relevant code is here:
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L73
