### ISSUE TITLE
NullReferenceException thrown from XmlCommentsIdHelper

### ISSUE THREAD

**Issue by SiCoe** [heldersepu/Swagger-Net#81]
Hi,

We've come across an issue using the Swagger-Net NuGet package in our site.

A `NullReferenceException` is thrown from within the `ExpandGenericArgsIfAny` method of `XmlCommentsIdHelper`.

After investigation I've managed to pinpoint the issue and recreate it using your Swagger.Net.Tests project. Please see my commit [8c491c36](https://github.com/SiCoe/Swagger-Net/commit/8c491c368f6688e418addc4d7cf0070f84b972f4). With the modified Controller, 21 of your existing tests fail with:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Swagger.Net.XmlComments.XmlCommentsIdHelper.ExpandGenericArgsIfAny(Type type, StringBuilder builder, IDictionary`2 genericParametersPositions) in <repo_dir>\Swagger-Net\Swagger.Net\Swagger\XmlComments\XmlCommentsIdHelper.cs:line 96
```

The issue lies with a nested class using generic types from the class it's nested into.

The tests go green if I put a null check on [line 89](https://github.com/heldersepu/Swagger-Net/blob/d37d33d7edb984ab83555720c3eead971a696fb6/Swagger.Net/Swagger/XmlComments/XmlCommentsIdHelper.cs#L89), changing:

```C#
if (type.IsGenericType)
```

to:

```C#
if (type.IsGenericType && genericParametersPositions != null)
```

Though I'm unsure if this is the correct solution.

Any help on this issue is appreciated.

**Comment by heldersepu** [comment]
Create a new test instead of modifying an existing one to make sure we don't break anything else...
And Yes send a PR and I will merge and publish...

if this is not the correct solution. is the best one yet

**Comment by heldersepu** [comment]
Thanks, New package uploaded:
https://www.nuget.org/packages/Swagger-Net/8.3.22.202
