### ISSUE TITLE
Nullable data type

### ISSUE THREAD

**Issue by chrno1209** [heldersepu/Swagger-Net#87]
Hi,
Is there anyway to display nullable data type on definitions?
Thanks.

**Comment by heldersepu** [comment]
Is there something that is not working? 
please describe your actual issue

**Comment by chrno1209** [comment]
This is not actually an issue, it is just a question where I want to show user that this definition's property is nullable on model view, so they know it.

**Comment by heldersepu** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by chrno1209** [comment]
@heldersepu thanks for your suggestion, as I notice that OAI v2 does not support nullable type, it support from v3 only :).
