### ISSUE TITLE
Locked to version 5.2.4 of System.Net.Http.Formatting

### ISSUE THREAD

**Issue by verzada** [heldersepu/Swagger-Net#89]
If I upgrade 
Microsoft.AspNet.WebApi.Client
Microsoft.AspNet.WebApi.Core
to the latest version of my project referencing Swagger-Net, I will get error when starting up the application because System.Net.Http.Formatting and Newtonsoft.Json version are hard coded into the app.config file.

The packages.config says it'll support 5.2.4 and above. Which is not correct.

To replicate:
Create a new web api project, add swagger-net 
Upgrade to the latest version of 
Microsoft.AspNet.WebApi.Client
Microsoft.AspNet.WebApi.Core
Newtonsoft.Json

Start up the web api project and it'll fail, because the current version of the dll's are newer than the ones that are referenced in the app.config of Swagger-Net.

Solution: remove the app.config file from the project.
Or under application in the project settings: turn off "Auto-generate binding redirects"

**Comment by heldersepu** [comment]
new version (8.3.23.1102) comming up

**Comment by heldersepu** [comment]
https://www.nuget.org/packages/Swagger-Net/8.3.23.1102

**Comment by verzada** [comment]
Hey. It's not solved quite yet.
The nuget references need to have **Specific version** set to **false**
Example Swagger-net project file
```xml
    <Reference Include="System.Net.Http.Formatting, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.AspNet.WebApi.Client.5.2.4\lib\net45\System.Net.Http.Formatting.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
```

You can also set the reference to false in Visual Studio. Just select the reference in the solution view and set "specific version" to false.

**Comment by heldersepu** [comment]
Submit a PR

**Comment by verzada** [comment]
Does it look okay enough to push out a new package?

**Comment by heldersepu** [comment]
Sorry I forgot to push...
https://www.nuget.org/packages/Swagger-Net/8.3.23.1103

**Comment by verzada** [comment]
Can confirm it works

I set the reference in the web.config like this:
``  
     <dependentAssembly>
        <assemblyIdentity name="System.Web.Http" publicKeyToken="31BF3856AD364E35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.7.0" />
      </dependentAssembly>
``
