### ISSUE TITLE
support oidc

### ISSUE THREAD

**Issue by kissstudio** [heldersepu/Swagger-Net#95]

**Comment by heldersepu** [comment]
sorry, you have to be more specific than that...

**Comment by kissstudio** [comment]
failed to authorize when using oauth authorization if add non resource type scope like openid of identity server.

it because responsetype ony has a token rather than id_token and token when do the oidc authorize. 

the iodc is some different from oauth. so it can not simply supported by injecting js and modify the resposne type.

**Comment by kissstudio** [comment]
can you please add suport to the oidc authroize feature :)
