### ISSUE TITLE
Missing xml route comments with array param []

### ISSUE THREAD

**Issue by Drenskin** [heldersepu/Swagger-Net#97]
Hello,

I have this route :

```c#
namespace ApiV5.Controllers
{
    public class OrdersController : ApiController
    {
        /// <summary>
        /// Get organization orders
        /// </summary>
        /// <param name="organizationSlug">The organization slug</param>
        /// <param name="from">from</param>
        /// <param name="to">to</param>
        /// <param name="userSearchKey">userSearchKey</param>
        /// <param name="pageIndex">pageIndex</param>
        /// <param name="pageSize">pageSize</param>
        /// <param name="continuationToken">continuationToken</param>
        /// <param name="formTypes">formTypes</param>
        /// <param name="retrieveOfflineDonations">retrieveOfflineDonations</param>
        /// <param name="withDetails">withDetails</param>
        public IHttpActionResult GetOrders(
            string organizationSlug,
            [FromUri] DateTimeOffset? from = null,
            [FromUri] DateTimeOffset? to = null,
            [FromUri] string userSearchKey = null,
            [FromUri] int pageIndex = 1,
            [FromUri] int pageSize = QueriesConstants.DefaultPageSize,
            [FromUri] string continuationToken = null,
            [FromUri] FormType[] formTypes = null,
            [FromUri] bool retrieveOfflineDonations = false,
            [FromUri] bool withDetails = false
        )
        {
            ...
        }
    }
}
```

In the XML documentation file generated, the method has this member name signature : 
`"M:ApiV5.Controllers.OrdersController.GetOrders(System.String,System.Nullable{System.DateTimeOffset},System.Nullable{System.DateTimeOffset},System.String,System.Int32,System.Int32,System.String,ApiV5.Models.Enums.FormType[],System.Boolean,System.Boolean)"`

But when trying to retrieve it for the xml comments, the method XmlCommentsIdHelper.GetCommentIdForMethod(...) generates the node this way : 
`"M:ApiV5.Controllers.OrdersController.GetOrders(System.String,System.Nullable{System.DateTimeOffset},System.Nullable{System.DateTimeOffset},System.String,System.Int32,System.Int32,System.String,ApiV5.Models.Enums.FormType[][],System.Boolean,System.Boolean)"`
with an extra [] on the array. So the filter ApplyXmlActionComments does not find the xml node, and the comments are missing on the action in swagger.

**Comment by heldersepu** [comment]
Workaround is easy don't use arrays in the uri...

And what is formtype ?

**Comment by heldersepu** [comment]
I remember a while back running into a similar issue:

https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/Controllers/ArrayTestController.cs#L61
`public List<Location> Get3([FromUri] List<Location> p)`
Had multiple issues 
- it was not set on the uri as I liked 
- it was not parsed correctly by swagger-ui

____

My workaround at the time was to use a json string
https://github.com/heldersepu/Swagger-Net-Test/blob/master/Swagger_Test/Controllers/ArrayTestController.cs#L72
receive that as a string and deserialize inside.

I hope that helps you

**Comment by Drenskin** [comment]
FormType is an enum, and we want to be able to retrieve/filter only certain form types.

I've changed my arrays T[]  to List<T>, but don't you think it is still a bug that the method does not generates the expected method name ?

**Comment by heldersepu** [comment]
Ye certainly a bug, but I don't think is worth the time to fix
