### ISSUE TITLE
versions published to nuget don't match releases in github

### ISSUE THREAD

**Issue by zlangner** [heldersepu/Swagger-Net#98]
https://github.com/heldersepu/Swagger-Net/releases shows the latest version as 8.3.23.104 but the latest version on https://www.nuget.org/packages/Swagger-Net/ is 8.3.25.402 published 19 days ago. Why are these not in line?

**Comment by heldersepu** [comment]
Just lazy me cutting corners... to save time because time is money

**Comment by zlangner** [comment]
Thanks. I was concerned that since they didn't line up this repo was officially the same as the nuget package.
