### ISSUE TITLE
Add filter for operations and make filtering case insensitive

### ISSUE THREAD

**Issue by nickschotaliya** [heldersepu/Swagger-Net#99]
Feature request: add filter for operations and make it case insensitive

**Comment by heldersepu** [comment]
The filter is a swagger-ui feature:
https://github.com/swagger-api/swagger-ui

Filtering already exists, but it is case sensitive:
http://swagger-net-test.azurewebsites.net/swagger/ui/index?filter=array
http://swagger-net-test.azurewebsites.net/swagger/ui/index?filter=Array

___
Also, I strongly recommend you to add a little more explanation to your feature requests, a one-line request like this is not going to be taken seriously

**Comment by nickschotaliya** [comment]
yes I know filter already exist but is there any option for make filtering case insensitive?

**Comment by heldersepu** [comment]
No
